version: 2.1
jobs:
  build_image:
    docker:
      - image: nixos/nix:2.3.6
    environment:
      NIXPKGS_ALLOW_BROKEN: 1

    steps:
      - run:
          name: Updating channels
          command: nix-channel --update

      - run:
          name: Install system dependencies
          command: nix-env -i openssh git

      - checkout

      - run:
          name: Build docker image
          command: nix-build --show-trace --argstr imageName $DOCKER_IMAGE_NAME --argstr tag ${CIRCLE_TAG:-$CIRCLE_BRANCH} nix/docker_image.nix

      - run:
          name: Hard-linking result to current directory
          command: ln $(readlink -f result) ./docker-image-teg.tar.gz

      - persist_to_workspace:
          root: .
          paths:
          - "./docker-image-teg.tar.gz"


  publish_tag:
    machine: true

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Load image
          command: |
            docker load -i docker-image-teg.tar.gz

      - run:
          name: Publish image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag $DOCKER_IMAGE_NAME:$CIRCLE_TAG $DOCKER_IMAGE_NAME:latest
            docker push $DOCKER_IMAGE_NAME:$CIRCLE_TAG
            docker push $DOCKER_IMAGE_NAME:latest

workflows:
  version: 2
  build-release:
    jobs:
      - build_image:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
      - publish_tag:
          requires: [ build_image ]
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
