version: 2.1
jobs:
  build_image:
    docker:
      - image: nixos/nix:2.3.6
    environment:
      NIXPKGS_ALLOW_BROKEN: 1

    steps:
      - run:
          name: Updating channels
          command: nix-channel --update

      - run:
          name: Install system dependencies
          command: nix-env -i openssh git

      - checkout

      # - restore_cache:
      #     name: Restore Cached Dependencies
      #     keys:
      #       - teg-{{ checksum "stack.yaml" }}-{{ checksum "teg.cabal" }}

      - run:
          name: Build docker image
          command: nix-build --argstr imageName $DOCKER_IMAGE_NAME --argstr tag $CIRCLE_TAG release.nix --show-trace

      - run:
          name: Copying result to current directory
          command: cp $(readlink -f result) ./docker-image-teg.tar.gz

      - persist_to_workspace:
          root: .
          paths:
          - "./docker-image-teg.tar.gz"

      # - save_cache:
      #     name: Cache Dependencies
      #     key: teg-{{ checksum "stack.yaml" }}-{{ checksum "teg.cabal" }}
      #     paths:
      #       - "/root/.stack"
      #       - ".stack-work"


  publish_tag:
    machine: true

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Load image
          command: |
            docker load -i docker-image-teg.tar.gz

      - run:
          name: Publish image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $DOCKER_IMAGE_NAME
            docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$CIRCLE_TAG
            docker push $DOCKER_IMAGE_NAME:$CIRCLE_TAG

workflows:
  version: 2
  build-release:
    jobs:
      - build_image:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
      - publish_tag:
          requires: [ build_image ]
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
