version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-16.14

    steps:
      - run:
          name: Install git/ssh
          command: apt-get update -y && apt-get install -y openssh-client git

      - checkout

      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - teg-{{ checksum "stack.yaml" }}-{{ checksum "teg.cabal" }}

      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup

      - run:
          name: Install node dependencies
          command: cd ui && npm install

      - run:
          name: Build Haskell binaries
          command: stack --no-terminal build --copy-bins

      - run:
          name: Codegen
          command: |
            export PATH=ui/node_modules/.bin:$PATH
            bin/teg --codegen

      - persist_to_workspace:
          root: .
          paths:
            - "Dockerfile-release"
            - "bin/teg"

      - run:
          name: Build Elm apps
          command: |
            cd ui
            npx elm make src/Homepage.elm --output _build/home.js
            npx elm make src/Main.elm --output _build/game.js

      - persist_to_workspace:
          root: ui
          paths:
            - "static"
            - "_build/home.js"
            - "_build/game.js"

      - save_cache:
          name: Cache Dependencies
          key: teg-{{ checksum "stack.yaml" }}-{{ checksum "teg.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"


  publish_tag:
    machine: true

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Build image
          command: |
            docker build -f Dockerfile-release -t $DOCKER_IMAGE_NAME .

      # - run:
      #     name: Publish image
      #     command: |
      #       echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      #       docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$CIRCLE_TAG
      #       docker push $DOCKER_IMAGE_NAME
      #       docker push $DOCKER_IMAGE_NAME:$CIRCLE_TAG

workflows:
  version: 2
  build-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
      - publish_tag:
          requires: [ build ]
          filters:
            # tags:
            #   only: /^\d+\.\d+\.\d+/
            # branches:
            #   ignore: /.*/
            branches:
              ignore: /release-test/
