FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  netbase \
  ca-certificates \
  libgmp-dev

RUN rm -rf /var/lib/apt/lists/*

# Fixes a crash when logging weird unicode stuff to STDOUT
ENV LC_ALL C.UTF-8

WORKDIR /opt/app

COPY ./bin/teg .

COPY ./ui/static static
COPY ./ui/static/_build/home.js static/_build
COPY ./ui/static/_build/game.js static/_build

CMD /opt/app/teg --server